### ISSUE TITLE
EDT

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-ar#1]
[EDT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-entrevista-ar/files/9834856/EDT.pdf)

**Comment by Rmz-Rigo** [comment]
Calificación: 18/20
La cantidad de imágenes no cumple con la rúbrica.
El reporte no tiene objetivo y descripción de la práctica.
La descripción de las imágenes no es clara.

**Comment by josealfredo79** [comment]
Revisado...
